/* File        : CONVERT.H
   Module      : CONVERT
   System      : None
   Description : The definition header file for the CONVERT module.
   Modified    : 07/09/91 DWP Initial coding.
   Notes       :
*/

#ifndef _CONVERT_MODULE
#define _CONVERT_MODULE

#include "Standard\standard.h"

/* Procedures and Functions. */

char * CONVERT_Base(CARDINAL_32 Base_10_Value, CARDINAL_16 Conversion_Base, char * Value);

#endif
