
cd \lib\asm\convert
call \build convert

rem cd \lib\asm\crt
rem call \build crt

cd \lib\asm\cursor
call \build cursor

cd \lib\asm\dir
call \build dir

cd \lib\asm\file
call \build file

cd \lib\asm\kb
call \build kb

cd \lib\asm\lzw
call \build lzw

cd \lib\asm\memory
call \build memory

cd \lib\asm\msdos
call \build msdos

cd \lib\asm\printer
call \build printer

cd \lib\c\array
call \build array

cd \lib\c\kb
call \build kb

cd \lib\c\math
call \build math

cd \lib\c\avl_tree
call \build avl_tree

cd \lib\c\list
call \build list

cd \lib\c\cle
call \build cle

cd \lib\c\convert
call \build convert

cd \lib\c\string
call \build string

cd \lib\c\date
call \build date

cd \lib\c\debug
call \build debug

cd \lib\c\dir
call \build dir

cd \lib\c\disk
call \build disk

cd \lib\c\file
call \build file

cd \lib\c\lzw
call \build lzw

cd \lib\c\text
call \build text

cd \lib\c\text_int
call \build text_int

cd \lib\c\menu
call \build menu

cd \lib\c\msdos
call \build msdos

cd \lib\c\port
call \build port

cd \lib\c\stack
call \build stack

cd \lib\c\time
call \build time

cd \lib\c\xbase
call \build xbase

cd \

