
cd \apps\ksg
call \build asm

cd \apps\ac
call \build ac

cd \apps\allocdsk
call \build allocdsk

cd \apps\boot
call \build boot

cd \apps\cal
call \build cal

cd \apps\cle
call \build cle

cd \apps\dump
call \build dump

cd \apps\editpath
call \build editpath

cd \apps\envedit
call \build envedit

cd \apps\fcomp
call \build fcomp

cd \apps\icenoout
call \build icenoout

rem cd \apps\kbclear
rem call \build kbclear

cd \apps\kbflags
call \build kbflags

cd \apps\kbsc
call \build kbsc

cd \apps\kbstate
call \build kbstate

cd \apps\ksg
call \build ksg

rem cd \apps\move
rem call \build move

cd \apps\prime
call \build prime

cd \apps\random
call \build random

cd \apps\read
call \build read

cd \apps\realname
call \build realname

cd \apps\reminder
call \build reminder

cd \apps\scan
call \build scan

cd \apps\switchar
call \build switchar

cd \apps\treedir
call \build treedir

cd \apps\xdate
call \build xdate

cd \apps\xdel
call \build xdel

cd \apps\xmd
call \build xmd

cd \

